{"name": "test_management_user_can_send_invite_user_email", "status": "passed", "description": "管理者ユーザで正常に招待メールを送信できることをテスト", "start": 1673748205510, "stop": 1673748205669, "uuid": "bea6657a-3720-40dc-b7d2-997e314a6f18", "historyId": "d26c38afe99260abf4cf521ac01f310b", "testCaseId": "bd1ae50ea20b17fb7388a8915b125c3c", "fullName": "application.tests.mail.test_email.TestInviteUser#test_management_user_can_send_invite_user_email", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "application.tests.mail"}, {"name": "suite", "value": "test_email"}, {"name": "subSuite", "value": "TestInviteUser"}, {"name": "host", "value": "eab8ab219ba9"}, {"name": "thread", "value": "309-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "application.tests.mail.test_email"}]}