{"name": "test_part_time_user_cannot_send_invite_user_email", "status": "passed", "description": "アルバイトユーザで招待メールを送信できないことをテスト", "attachments": [{"name": "log", "source": "16a0225b-99b6-47f9-b516-561d9d1b83a7-attachment.txt", "type": "text/plain"}], "start": 1673748205961, "stop": 1673748206092, "uuid": "b69715ed-6ab9-4d21-9384-9cddc1b2f8cf", "historyId": "6773833594ad38213a17b996ee228d26", "testCaseId": "d371c0baced07bbc4db86179c84b7740", "fullName": "application.tests.mail.test_email.TestInviteUser#test_part_time_user_cannot_send_invite_user_email", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "application.tests.mail"}, {"name": "suite", "value": "test_email"}, {"name": "subSuite", "value": "TestInviteUser"}, {"name": "host", "value": "eab8ab219ba9"}, {"name": "thread", "value": "309-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "application.tests.mail.test_email"}]}